### Requires these components

REQUIRES += common/c/reg
REQUIRES += hal/3pp/broadcom_refsw/18.1
REQUIRES += hal/3pp/broadcom_refsw/18.2.1
REQUIRES += firmware/3pp/bolt_1_26_rbl
REQUIRES += firmware/3pp/bolt_rbl
REQUIRES += firmware/3pp/brcm_bolt_rbl
### Component specification

